### ISSUE TITLE
Crash placing blocks on the abstract bus

### ISSUE THREAD

**Issue by neronix17** [LordFokas/StargateTech2#108]
As the title says
Crash Log: http://pastebin.com/DC801AeD

**Comment by LordFokas** [comment]
Oh I see, it's a problem on my side... more or less.
Since CoFH stopped shipping the BC wrench interface, it causes an error because I use that interface and relied on CoFH.

A short term solution would be using older CoFH stuff, but that means no cool new features.
Unfortunately I can't fix this until v0.8 comes out, but it should be in v0.8 itself.

**Comment by LordFokas** [comment]
Alright, fixed in v0.7.8
