### ISSUE TITLE
0.7.7(1.7.10) Shielding Set up

### ISSUE THREAD

**Issue by messra20** [LordFokas/StargateTech2#110]
Im trying to figure out if the whole shield emitter/controller set up will actually work, and produce a shield to stop players and what not.Even though ive got everything i need: a particle ionizer,Shield Emitters, Shield Controllers and are feeding ionized particles to each of the controllers. The shield doesnt seem to want to show up. Am i missing something involving a computer and abstract cables?

**Comment by LordFokas** [comment]
Yes you are. Right now you need to use a computer to enable or disable the shields.
In v0.8.x you'll be able to do it with redstone (although right now that behavior is a bit buggy).

I'd rather have questions like those directed to the forum thread instead of issues in the tracker.

Also, consider upgrading to v0.7.8, it fixes a nasty crash that you'll get if you upgrade to recent CoFH mods.

**Comment by messra20** [comment]
thanks for the pointers.
