### ISSUE TITLE
Um, crash with Shield Controller.

### ISSUE THREAD

**Issue by gjgfuj** [LordFokas/StargateTech2#79]
I seem to be crashing when I open my shield controller on the server. I don't know why.

The crash log is: http://openeye.openmods.info/crashes/c20579578830f5c1ada0a390edd0acb2

**Comment by cvelde** [comment]
http://pastebin.com/rrtm6YWY

Really weird, first it only appeared to happen after entering "e" multiple times (trying to close the gui) now it happens every time i open it

**Comment by JoshTheEnder** [comment]
@cvelde mind making a new issue for your one? also try with just SGTech and it's dependencies and see if you still get the error (because SGTech isnt in the stack trace)

**Comment by LordFokas** [comment]
Alright, can you get us the full FML log?
I'm not going to attempt to fix this at least yet because in the next release we'll have a new GUI system.
However I'd like to understand the issue so that if it's related to the containers and not the GUI itself I can fix it in v0.8, and even if not, I want to learn from it, because that bug is quite a sneaky bastard.

**Comment by LordFokas** [comment]
I'm dismissing this as a false positive. If it ever happens again, take your time to report it ##PROPERLY## or don't even bother coming here.
